# Generated by Django 3.2.3 on 2021-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='questions',
            field=models.ManyToManyField(to='tasks.Question'),
        ),
        migrations.DeleteModel(
            name='UserQuestions',
        ),
    ]
