# Generated by Django 3.2.3 on 2021-05-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0002_auto_20210526_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='tasks.Question'),
        ),
    ]
