# Generated by Django 3.2.3 on 2021-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210527_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
