# Generated by Django 3.2.3 on 2021-05-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_completed_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
